robot:
  name: ur10srh
  manipulators:
    right_manipulator:
      side: right
      arm:
        name: ur10
        main_group: manipulator
        other_groups:
          - endeffector
        moveit_path:
          package: sr_multi_moveit_config
          relative_path: /config/ur
        extra_groups_config_path: /config
        group_states:
          - home
          - up
    left_manipulator:
      side: left
      arm:
        name: ur10
        main_group: manipulator
        other_groups:
          - endeffector
        moveit_path:
          package: sr_multi_moveit_config
          relative_path: /config/ur
        extra_groups_config_path: /config
        group_states:
          - home
          - up

ra_sr_ur_robot_hw:
  # No hand
  payload_mass_kg: 0.0

la_sr_ur_robot_hw:
  # No hand
  payload_mass_kg: 0.0

/gazebo_ros_control:
  pid_gains:
    la_shoulder_pan_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    la_shoulder_lift_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    la_elbow_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    la_wrist_1_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    la_wrist_2_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    la_wrist_3_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    ra_shoulder_pan_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    ra_shoulder_lift_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    ra_elbow_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    ra_wrist_1_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    ra_wrist_2_joint:
      p: 100.0
      i: 0.01
      d: 10.0
    ra_wrist_3_joint:
      p: 100.0
      i: 0.01
      d: 10.0
